### PR TITLE
Add Cayman stylesheet

### PR DESCRIPTION
**Pull request by Mather-Games**
Hello! I decided i might try to make your website look a little better with CSS from Github that i think looks nice. Also, for the contact form i recommend Google Forms!

### CODE REVIEW

**Comment by Rowan-McAlpin** [comment]
Hmmm... Do you know if there is a way to preview it without merging it? I want to test it out before committing.

**Comment by Mather-Games** [comment]
Copy the changes and paste them in a document

**Comment by Rowan-McAlpin** [comment]
k I'll try that

**Comment by Rowan-McAlpin** [comment]
Thanks for your suggestion, Mather! However, we cannot accept your fork. If you would like to know more, please contact me.

**Pull request closed without merging**
